version: "3"
services:
  date-apps-be:
    image: "date-apps-be/development:latest"
    container_name: "date-apps-be-development"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../../:/app
      - go_dir:/go
    command: |
      deployments/development/start.sh
    environment:
      APP_PORT: 0.0.0.0:8080
      CORS_ORIGINS: "http://localhost:3000"
      APP_ENV: development
      DBMASTERUSER: root
      DBMASTERPASS: root
      DBMASTERHOST: date_app_db
      DBMASTERPORT: 3306
      DBMASTERNAME: date_app
      DBMASTERMAXIDLECONN: 10
      DBMASTERMAXOPENCONN: 50
      DBSLAVEUSER: root
      DBSLAVEPASS: root
      DBSLAVEHOST: date_app_db
      DBSLAVEPORT: 3306
      DBSLAVENAME: date_app
      DBSLAVEMAXIDLECONN: 10
      DBSLAVEMAXOPENCONN: 50
      JWT_RS256_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS2dJQkFBS0NBZ0VBc1B0aEtDaGdNQmhpOS9lT2lKdExLTEtrY0FGK1pTZG1nL29SaERQcy9oZzE4QUNlCng3cWNsbEhUYjVYQjM2djF2ekJCVjlJeGIrOUJXT3hYYkpsRGUyUmZIYnM4MnN3dHVpSjhWL25rK1NZbi91ZlIKTDMxNkZoWE53djB3VDJzVFdqU09JZUdGczZPQ0JjbVhGQncrRGlTTVdzVHJYS3JyZzI4aml3dXZJRDZqNTV0dQp0TUFqZ2ZRaml1OVhwSmJieDNxZmVqZjBSVm5nTTBUUmVReW1ZZUVyaEFSdEdYL3dLL2NTT2E0aEo1cDNXUjZyCmlGUFZtcGxMb1RNdzZRajhkMU5Ob2ZISS81SXF2Zm1oNXF5dUorUXp1eUdpVlhrM1MzbGRld0ppbzlrNkNSb1kKZGkwcDNvVGlTUnhIc0RPam1YY1RnU0xQY3lLZ09XWXl0eE9ic1cvTzdmdW53T2dLSGZrMG1CYkdrQjR2alM1LwpONXhxZ3o4OE9aWnd6OHg0anQxSldmRXdqREVRUTZBeS96dWFXdjBKZGUrN2prc1hHMWVuWGpqb2NQdkYwV1ltCjd2aXIybGpNWjdXMWJ6T3lMWDB6VDVZNVdlMjRLQ1Fud2tVVHY3UlNPU3VIK3lQaE1TcTFPeGZOTGZBYlh5YTkKSEtrUlpNUGpaLzlFZDFtRGRCVDZzeGNnL1NOeCt2WWhIalhCOHBPQVBNNVJSN0xpKzg1TDhtVE51Q1grM1NPVgp5bHVKTkRFOVk0b1lmbXViMVl0U2hXTzFkWEszVVFUQVhCcVFYcmIwSTZMakppc0sydjR1YXRNZUlrWmJRUlhECndhUU9Zd0JucWQ3NDRNMVRaYU0wcXZBQis5TjRYTlF2TkpBNVRxQ2xMdldqblpCajdwOXJ6U1JFUURFQ0F3RUEKQVFLQ0FnQlRBSkpBVXk5Slh5YUxSUDhEOGxEOWRVckpmT25hWnZBZFZWcUJ0aGlmMHByNVJGRXpPc0hWZmVxNwptbkNpaGZOckJ5YWVHV1kyS085czFPcnJjN1hDV1FDQzRSMVpRQWp5RXRwZUtFVEsxS3BOVWtzNUNwQUhhNUprCnNIbkh4Vi8rSGtmS2ZBcEloWmFsUURZcXFGUXlMZEhsZ0JVaUVNY0RqVXdPR2h5Mzhxak1Kb2wxRytlTE93U3cKVkMrMmNVb0I4L0IzVVdhdVg4aFdReUE2dFVRVEE1ZDFBdDVuNXlpc2RlT0dTYlFpN3I2cWZVZlZWL3dGMVg4eQp5dDlWYTNGOFJRVlR2aUdXT3VidzBmS3NUTEFnNVZXZG5kaVVYWlVoUUhvbkJxZGNVTFIzTUZYb2xxWGNSbFlhCkU3bExXZXlRUE5oWTZBcUM1T3BnQVI0bjNucFZwV0thKzhwSm5DY3Y0aUJZZ3BFUVBkY3RLOFBkQnh3d09GQloKWk9oU2FiUnNhNGFvSlVESTlOZHFwd1NYeW1VR2pPL2wxRU9KTmNZbmxUKzRDMWc5RE1nRzlFOXpUVGZHVVhvZwpPb013bERWREY3bUJNcGlGa1NhQngxWml3bnUycVJWWkxUazJmb2x5K2srWGpYN2gwRUhoMWhjV05uU1Y2Q2RuCmRBWkY2TDRCaEdDb25sRFRYMjAwaTQ1M0lUWFlwbDBaMlJmRVNVeW5PNjV1R1BJMS84aVl6dkwxOVVRNWk2RmEKUWQ3RlZQQzV5QWgyY0RDNUpmekl4WnkvbVBuOW5LWmxycUdEbytuL01LT2p1cE94Qkg1djAzT1o3Z0JWekl2SgpQUUI4d04ydHUvSjJJT0J5Yk9aQUp5YXV5M0hBeUpCc2NZQ2YrT2JnU29pWXk3ZmlRUUtDQVFFQTNJRVE0aVBhClpmcG05cytIWXhaNXR1ekJ5NytOOFR3VUdnV1ArdFNkemhFTGVGME8wVVByUWs5OWNSS0E3bmVVYWs4bnhONE8KbGh0NjNWWDU5Yk9XTlV1dmd3VFlsK1ZjMEZMaHlFRlVkenBTeFp6MXFVZTNxcGFNak94Mzd4VzlqV0lVaC9wSwo4VmNnZDFReGJ2UHFkZFNneWlGWnFFK0x1bEE5aXBvZkdzL1UxRnVnNWcxb21CajdpNG9MV3JsVm5sdURkOHpPClRCM0NsTmw5cFM3RmlYK0NSTHZKd0FCSkx1RTh6bnNGWTI2QU51OFF4TXNGV2hQeUtZS1czTnpDcExHclV5ZHkKZ05OdlFaeDc3MDY3VGZCSm5ORGJka3FsRVdVTHg2RHJLNXR1REUwQi81T0Fwa3Z0YS90dVdHVURjUVl4ZU11OApEcUU1Z1RHNGhScHVCd0tDQVFFQXpYakZobnN4ZTJROHVwQkpsTkw2c1k5MmVOeWtIUXVYV29Pc3d5emI0MjJYCnBwaTAxa25MaDd5bHJrUlo3YjdSNGwycDg1MnZ2Tm5Nd254MVhJWTFmSGtySE9xV0VwY205NzhTblptWHJSZ2MKTE1Fd0hQaWcrM2ZPSGFCOG9zUFVSUFNudjhrWHoreXEvUytVejdWSnY0cjFFUnRUZTBVa29BMWZSQzBnakg3RApuUmFpUWpCWjUvWVZNdHhaT0w1TmtGa1lUYlZuWnVWVjhLTklUMmo4RG5Nb0NMdFBrSVc2eE5Xamt3Y1hVWTRYCjlJMlVaaFh2K1VXUUpPUG9QZU5sZ3RXUzdDQUgxNjNkMnU0L3FhVXh1dHE5T0d1b2R0ZE0wWXV5cklTbnFUcFAKbU1UY1dldjgvMlJNSFI0aTBaeDh6cnBtbmVyS3hjMG9wV3B0ZVF0U0J3S0NBUUVBc1I4UGs4Y2U4Sm1DU2JFTAozSUU2UmNES0xzTHczcHpXdk14SkNqL3RmcEJjZVZPdXlsUFhUdzJSQXRuTkxVQnF2RFpYQ0tFaWNGc2toMVEvCms2aXMrS1NTR0JrMWJsWDBCdmI4bkNJMkdndUVYMjRrT3RUNzZKQkQyQk0raDVNY0RzeUJGM1RxN0ErRGFiYjgKZWxaOXVDYVMvYXBxWFhPQUZxbkx0V0QxcVZEV2Nib2tkWWJCeEtNVXM5S3dLakVEWUUrOE8rZ01za0daZ24xdAptdGtHSGR1SnBYSityYmJORWxZa3hPczJ1ZGNTTUk0NkZ3bkpnOERQM1o0alZzZ1JwYjk5a2k3Mm9CcTJuS3A1Ck54STBESGYrZVhPZlJkYlIzelllanoxb2lqK3cxenFvWjBaeHFhTUYxSjVEMWNkV1MxeWhNcG5jdHBlMUhGejMKRGh2YjB3S0NBUUVBdUFlMWtxK0FNQzRsSGt2aE80U0R1TWp2cVd5bEtNYWE5eHo4ZllzT0h2S25ZelZlc3BkQgp6Zjh1dlpqR211UFFCRmt6d05pNDhBSjdISzV3UjBDRlkwajdUbGpsdFJ6Z2NBRVk0VU1SMEp6SmoyUXdmYUpLClBUQ2UwWFpPYTFIT0t6eWRpbTdIL3hqUVJSaDZ4bFp2Q1RtaUtZSTZFU3hxazFlbXZkOVZTY0MzMzFqSVYxUUwKRW5FYnA0UW4vV1NrLytac21CMGowY3NTWUFjKzJyRURJTVlQVTFMQS9vWm9NNmZOYkFCcjZFWEdPdWtid3h0ZQo1ZnBpRWtoMldBZjFnV3RjdmxRcDhnanRyZ3E1eG00SXpuemdBVXFiaG1WcmpqcjYrdjJOVlVxK3crdCtHS1ArCjQ1ZW5mR1RqZHE0Y011Uk15Si9rb2FrUkFLY0VDZWdUdlFLQ0FRRUF5bXYvaTYwVUl5VVF2SXRRWU9rTVBWZ1oKek43OFFKQ1ZVRC9DanRjWUhjb05DamNHZ2NlMlNFU1BxZ3NGeitueDBSRjR0TlpjSGhRS2V3TURoU3p0L3ZraQpwaTJsWDV5N3hDTDVXejlJaXN3aEtGZnlJQmJBNVI4bWpQdlQ5TDhUSWFBemFVd09VdCtCOGJKdXEwTXBEVUhxCm1KVmFsV1g4Szd0Ujlac3NDTUZnSExGMmxaNDVaNGRLMDRtZXREWHV3WXRuMEtKSmhOaXk3ZXBodGdWTnI4WWEKV0VTQ1loWTh6ZWtHc0dob3lzYmRFWmFmWnU2cTZwanZKUHcwZ1VTZVBRTHFma2RxbXdNSkxEVnZiRE5nZTlLMQplczRVT1JJeXNvSFpTaUJyNU1UT0xaTSswY1Y3bCtJU3lFbEJYcnFQZzRoRXhvaFRzMzFLNDgwd3hFdFJBUT09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
      JWT_RS256_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFzUHRoS0NoZ01CaGk5L2VPaUp0TApLTEtrY0FGK1pTZG1nL29SaERQcy9oZzE4QUNleDdxY2xsSFRiNVhCMzZ2MXZ6QkJWOUl4Yis5QldPeFhiSmxECmUyUmZIYnM4MnN3dHVpSjhWL25rK1NZbi91ZlJMMzE2RmhYTnd2MHdUMnNUV2pTT0llR0ZzNk9DQmNtWEZCdysKRGlTTVdzVHJYS3JyZzI4aml3dXZJRDZqNTV0dXRNQWpnZlFqaXU5WHBKYmJ4M3FmZWpmMFJWbmdNMFRSZVF5bQpZZUVyaEFSdEdYL3dLL2NTT2E0aEo1cDNXUjZyaUZQVm1wbExvVE13NlFqOGQxTk5vZkhJLzVJcXZmbWg1cXl1CkorUXp1eUdpVlhrM1MzbGRld0ppbzlrNkNSb1lkaTBwM29UaVNSeEhzRE9qbVhjVGdTTFBjeUtnT1dZeXR4T2IKc1cvTzdmdW53T2dLSGZrMG1CYkdrQjR2alM1L041eHFnejg4T1pad3o4eDRqdDFKV2ZFd2pERVFRNkF5L3p1YQpXdjBKZGUrN2prc1hHMWVuWGpqb2NQdkYwV1ltN3ZpcjJsak1aN1cxYnpPeUxYMHpUNVk1V2UyNEtDUW53a1VUCnY3UlNPU3VIK3lQaE1TcTFPeGZOTGZBYlh5YTlIS2tSWk1QalovOUVkMW1EZEJUNnN4Y2cvU054K3ZZaEhqWEIKOHBPQVBNNVJSN0xpKzg1TDhtVE51Q1grM1NPVnlsdUpOREU5WTRvWWZtdWIxWXRTaFdPMWRYSzNVUVRBWEJxUQpYcmIwSTZMakppc0sydjR1YXRNZUlrWmJRUlhEd2FRT1l3Qm5xZDc0NE0xVFphTTBxdkFCKzlONFhOUXZOSkE1ClRxQ2xMdldqblpCajdwOXJ6U1JFUURFQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
      JWT_EXPIRATION: 43200 # in minutes
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    container_name: date_app_db
    environment:
      - MYSQL_DATABASE=date_app
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
volumes:
  db:
    driver: local
  go_dir:
    driver: local
