// Code generated by mockery v2.46.0. DO NOT EDIT.

package mockrepository

import (
	context "context"
	model "date-apps-be/internal/model"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// PremiumConfigRepository is an autogenerated mock type for the PremiumConfigRepository type
type PremiumConfigRepository struct {
	mock.Mock
}

// AddSortQuery provides a mock function with given fields: query, allowedFields, sortBy
func (_m *PremiumConfigRepository) AddSortQuery(query string, allowedFields []string, sortBy string) (string, error) {
	ret := _m.Called(query, allowedFields, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for AddSortQuery")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string, string) (string, error)); ok {
		return rf(query, allowedFields, sortBy)
	}
	if rf, ok := ret.Get(0).(func(string, []string, string) string); ok {
		r0 = rf(query, allowedFields, sortBy)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, []string, string) error); ok {
		r1 = rf(query, allowedFields, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddSortQueryWithPrefix provides a mock function with given fields: query, allowedFields, sortBy
func (_m *PremiumConfigRepository) AddSortQueryWithPrefix(query string, allowedFields map[string]string, sortBy string) (string, error) {
	ret := _m.Called(query, allowedFields, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for AddSortQueryWithPrefix")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]string, string) (string, error)); ok {
		return rf(query, allowedFields, sortBy)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string, string) string); ok {
		r0 = rf(query, allowedFields, sortBy)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string, string) error); ok {
		r1 = rf(query, allowedFields, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Begin provides a mock function with given fields:
func (_m *PremiumConfigRepository) Begin() (*sql.Tx, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sql.Tx, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Commit provides a mock function with given fields: tx
func (_m *PremiumConfigRepository) Commit(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exec provides a mock function with given fields: ctx, tx, query, args
func (_m *PremiumConfigRepository) Exec(ctx context.Context, tx *sql.Tx, query string, args []interface{}) (sql.Result, error) {
	ret := _m.Called(ctx, tx, query, args)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, []interface{}) (sql.Result, error)); ok {
		return rf(ctx, tx, query, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, []interface{}) sql.Result); ok {
		r0 = rf(ctx, tx, query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, string, []interface{}) error); ok {
		r1 = rf(ctx, tx, query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOffset provides a mock function with given fields: page, limit
func (_m *PremiumConfigRepository) GetOffset(page uint64, limit uint64) uint64 {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetOffset")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func(uint64, uint64) uint64); ok {
		r0 = rf(page, limit)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// GetPremiumConfigByUID provides a mock function with given fields: ctx, uid
func (_m *PremiumConfigRepository) GetPremiumConfigByUID(ctx context.Context, uid string) (*model.PremiumConfig, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetPremiumConfigByUID")
	}

	var r0 *model.PremiumConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.PremiumConfig, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.PremiumConfig); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PremiumConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPremiumConfigs provides a mock function with given fields: ctx, page, limit
func (_m *PremiumConfigRepository) GetPremiumConfigs(ctx context.Context, page uint64, limit uint64) ([]*model.PremiumConfig, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPremiumConfigs")
	}

	var r0 []*model.PremiumConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]*model.PremiumConfig, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []*model.PremiumConfig); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PremiumConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Master provides a mock function with given fields:
func (_m *PremiumConfigRepository) Master() *sql.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Master")
	}

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// NewNullString provides a mock function with given fields: str
func (_m *PremiumConfigRepository) NewNullString(str *string) sql.NullString {
	ret := _m.Called(str)

	if len(ret) == 0 {
		panic("no return value specified for NewNullString")
	}

	var r0 sql.NullString
	if rf, ok := ret.Get(0).(func(*string) sql.NullString); ok {
		r0 = rf(str)
	} else {
		r0 = ret.Get(0).(sql.NullString)
	}

	return r0
}

// Query provides a mock function with given fields: ctx, query, dest, args
func (_m *PremiumConfigRepository) Query(ctx context.Context, query string, dest []interface{}, args []interface{}) error {
	ret := _m.Called(ctx, query, dest, args)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}, []interface{}) error); ok {
		r0 = rf(ctx, query, dest, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rollback provides a mock function with given fields: tx
func (_m *PremiumConfigRepository) Rollback(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Slave provides a mock function with given fields:
func (_m *PremiumConfigRepository) Slave() *sql.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Slave")
	}

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// NewPremiumConfigRepository creates a new instance of PremiumConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPremiumConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PremiumConfigRepository {
	mock := &PremiumConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
