// Code generated by mockery v2.46.0. DO NOT EDIT.

package mockrepository

import (
	context "context"
	dto "date-apps-be/internal/usecase/user_match/dto"

	mock "github.com/stretchr/testify/mock"

	model "date-apps-be/internal/model"

	sql "database/sql"
)

// UserMatchRepository is an autogenerated mock type for the UserMatchRepository type
type UserMatchRepository struct {
	mock.Mock
}

// AddSortQuery provides a mock function with given fields: query, allowedFields, sortBy
func (_m *UserMatchRepository) AddSortQuery(query string, allowedFields []string, sortBy string) (string, error) {
	ret := _m.Called(query, allowedFields, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for AddSortQuery")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []string, string) (string, error)); ok {
		return rf(query, allowedFields, sortBy)
	}
	if rf, ok := ret.Get(0).(func(string, []string, string) string); ok {
		r0 = rf(query, allowedFields, sortBy)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, []string, string) error); ok {
		r1 = rf(query, allowedFields, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddSortQueryWithPrefix provides a mock function with given fields: query, allowedFields, sortBy
func (_m *UserMatchRepository) AddSortQueryWithPrefix(query string, allowedFields map[string]string, sortBy string) (string, error) {
	ret := _m.Called(query, allowedFields, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for AddSortQueryWithPrefix")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]string, string) (string, error)); ok {
		return rf(query, allowedFields, sortBy)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string, string) string); ok {
		r0 = rf(query, allowedFields, sortBy)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string, string) error); ok {
		r1 = rf(query, allowedFields, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Begin provides a mock function with given fields:
func (_m *UserMatchRepository) Begin() (*sql.Tx, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sql.Tx, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Commit provides a mock function with given fields: tx
func (_m *UserMatchRepository) Commit(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUserMatch provides a mock function with given fields: ctx, userMatch
func (_m *UserMatchRepository) CreateUserMatch(ctx context.Context, userMatch *model.UserMatch) error {
	ret := _m.Called(ctx, userMatch)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserMatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserMatch) error); ok {
		r0 = rf(ctx, userMatch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exec provides a mock function with given fields: ctx, tx, query, args
func (_m *UserMatchRepository) Exec(ctx context.Context, tx *sql.Tx, query string, args []interface{}) (sql.Result, error) {
	ret := _m.Called(ctx, tx, query, args)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, []interface{}) (sql.Result, error)); ok {
		return rf(ctx, tx, query, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, []interface{}) sql.Result); ok {
		r0 = rf(ctx, tx, query, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, string, []interface{}) error); ok {
		r1 = rf(ctx, tx, query, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvailableUsers provides a mock function with given fields: ctx, userUID, page, limit
func (_m *UserMatchRepository) GetAvailableUsers(ctx context.Context, userUID string, page uint64, limit uint64) ([]*model.User, error) {
	ret := _m.Called(ctx, userUID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableUsers")
	}

	var r0 []*model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) ([]*model.User, error)); ok {
		return rf(ctx, userUID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint64, uint64) []*model.User); ok {
		r0 = rf(ctx, userUID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint64, uint64) error); ok {
		r1 = rf(ctx, userUID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOffset provides a mock function with given fields: page, limit
func (_m *UserMatchRepository) GetOffset(page uint64, limit uint64) uint64 {
	ret := _m.Called(page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetOffset")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func(uint64, uint64) uint64); ok {
		r0 = rf(page, limit)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// GetTotalUserMatchToday provides a mock function with given fields: ctx, userUID
func (_m *UserMatchRepository) GetTotalUserMatchToday(ctx context.Context, userUID string) (int, error) {
	ret := _m.Called(ctx, userUID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalUserMatchToday")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userUID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserMatchTodayByUserUIDAndMatchUID provides a mock function with given fields: ctx, userUID, matchUID
func (_m *UserMatchRepository) GetUserMatchTodayByUserUIDAndMatchUID(ctx context.Context, userUID string, matchUID string) (*model.UserMatch, error) {
	ret := _m.Called(ctx, userUID, matchUID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserMatchTodayByUserUIDAndMatchUID")
	}

	var r0 *model.UserMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.UserMatch, error)); ok {
		return rf(ctx, userUID, matchUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.UserMatch); ok {
		r0 = rf(ctx, userUID, matchUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userUID, matchUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserMatches provides a mock function with given fields: ctx, d
func (_m *UserMatchRepository) GetUserMatches(ctx context.Context, d dto.GetUserMatches) ([]*model.UserMatch, error) {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for GetUserMatches")
	}

	var r0 []*model.UserMatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetUserMatches) ([]*model.UserMatch, error)); ok {
		return rf(ctx, d)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetUserMatches) []*model.UserMatch); ok {
		r0 = rf(ctx, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GetUserMatches) error); ok {
		r1 = rf(ctx, d)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Master provides a mock function with given fields:
func (_m *UserMatchRepository) Master() *sql.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Master")
	}

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// NewNullString provides a mock function with given fields: str
func (_m *UserMatchRepository) NewNullString(str *string) sql.NullString {
	ret := _m.Called(str)

	if len(ret) == 0 {
		panic("no return value specified for NewNullString")
	}

	var r0 sql.NullString
	if rf, ok := ret.Get(0).(func(*string) sql.NullString); ok {
		r0 = rf(str)
	} else {
		r0 = ret.Get(0).(sql.NullString)
	}

	return r0
}

// Query provides a mock function with given fields: ctx, query, dest, args
func (_m *UserMatchRepository) Query(ctx context.Context, query string, dest []interface{}, args []interface{}) error {
	ret := _m.Called(ctx, query, dest, args)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}, []interface{}) error); ok {
		r0 = rf(ctx, query, dest, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rollback provides a mock function with given fields: tx
func (_m *UserMatchRepository) Rollback(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Slave provides a mock function with given fields:
func (_m *UserMatchRepository) Slave() *sql.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Slave")
	}

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// NewUserMatchRepository creates a new instance of UserMatchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserMatchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserMatchRepository {
	mock := &UserMatchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
